CREATE SCHEMA IF NOT EXISTS exercicio1;

CREATE TABLE IF NOT EXISTS exercicio1.t_user(
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	email VARCHAR(254) NOT NULL UNIQUE,
	password VARCHAR(128) NOT NULL
);


