CREATE SCHEMA IF NOT EXISTS exercicio1;

CREATE TABLE IF NOT EXISTS exercicio1.usuario(
	userid BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nome VARCHAR(120) NOT NULL,
	email VARCHAR(320) NOT NULL UNIQUE,
	senha VARCHAR(128) NOT NULL
);

